import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header flex items-center justify-between text-white p-4 shadow-md">
          <Link
            href="/signin"
            className="px-4 py-2 bg-white text-black rounded-md font-semibold hover:bg-gray-200 transition"
          >
            Sign In
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
